export const ADD_EXAMPLE = 'ADD_EXAMPLE';
export const DELETE_EXAMPLE = 'DELETE_EXAMPLE';
export const SELECT_EXAMPLE = 'SELECT_EXAMPLE';

export const TRY_AUTH = 'TRY_AUTH';

export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';

export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';